### ISSUE TITLE
Novo endpoint para trazer frequências de um evento

### ISSUE THREAD

**Issue by itepifanio** [PETCC-UFRN/ePET#105]
Atualmente temos esses endpoints de frequência:

![Screenshot from 2020-06-14 20-12-46](https://user-images.githubusercontent.com/6730205/84606308-7a0b6900-ae7b-11ea-9295-62027f0c31ae.png)

Atualmente eu recupero se o cara teve frequência cadastrada através da /api/frequencia-pessoa/{id_participante}/{id_evento} só que usando ela se o evento tiver 30 pessoas serão realizadas 30 requisições pro backend e isso vai afetar a performance.

Vou precisar de um novo endpoint /api/frequencia/{id-evento} que me devolva todas as frequencias das pessoas no determinado evento. Idealmente o endpoint me retornaria um json do tipo:

```
{
    {
         participanteId: 1,
         periodosEvento: {
             0: {
                 idPeriodoEvento: 1,
                 frequenciaCadastrada: true,
             },
             1: {
                 idPeriodoEvento: 2,
                 frequenciaCadastrada: false,
             }
        },
    }
}
``` 

Com esse json eu consigo renderizar as frequências como checkbox e marcar as que já foram cadastradas

![Screenshot from 2020-06-14 20-09-31](https://user-images.githubusercontent.com/6730205/84606552-7ed11c80-ae7d-11ea-839a-c2bb96e16204.png)

**Comment by Danhfg** [comment]
O endpoint é /api/frequencia-evento/{id_evento}

**Comment by Danhfg** [comment]
Quando a pr #106 for aprovada o endpoint estará no ar
