### ISSUE TITLE
Não consigo acessar anexo de evento

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#113]
Eu tentando acessar os anexos de um evento. Verifiquei que o arquivo anexo tinha sido feito o upload corretamente. Trata-se do evento `idEvento = 30`. Abaixo segue o erro.

```
{
"titulo":"Recuso não encontrado",
"status":404,
"detalhes":"Nenhum anexo cadastrado.","timestamp":1595518590275,
"mensagem":"br.ufrn.ePET.error.ResourceNotFoundException"
}
```

**Comment by Danhfg** [comment]
Qual rota você utilizou ?

**Comment by Danhfg** [comment]
Qual rota você utilizou?

**Comment by Danhfg** [comment]
/anexos-evento/{id} ?

**Comment by Samuellucas97** [comment]
Sim foi esse `/anexos-evento/` com o `id = 30`

**Comment by Samuellucas97** [comment]
Identifiquei que o problema era no front
