### ISSUE TITLE
Edição de notícia

### ISSUE THREAD

**Issue by itepifanio** [PETCC-UFRN/ePET#40]
Seguindo o padrão da API, para tentar editar uma notícias passamos o id da notícia que queremos editar no endpoint de cadastro ` noticia-cadastro/{id} ` 

![Screenshot from 2020-05-01 22-18-29](https://user-images.githubusercontent.com/6730205/80851719-cb2c0a00-8bf9-11ea-929e-3b80ecb2d37a.png)

Porém notamos que consta na documentação que o id a ser passado é o de um petiano:

![Screenshot from 2020-05-01 21-54-12](https://user-images.githubusercontent.com/6730205/80851734-e9920580-8bf9-11ea-8c05-c10ea2ce801e.png)

Passando o id da notícia obtemos o seguinte erro:

![Screenshot from 2020-05-01 22-20-56](https://user-images.githubusercontent.com/6730205/80851772-0e867880-8bfa-11ea-843e-63ae99754705.png)

Mas passando o id do petiano isso não garante que estamos editando a notícia, como seria feita essa edição?

**Comment by Confuzo** [comment]
@itepifanio Posso fechar essa issue?

**Comment by itepifanio** [comment]
> @itepifanio Basta mudar o id da noticia dentro do body via POST. Posso fechar essa issue?

Pode sim, resolvido.
