### ISSUE TITLE
Tornar o código da disciplina como único

### ISSUE THREAD

**Issue by Danhfg** [PETCC-UFRN/ePET#44]

**Comment by Confuzo** [comment]
@Danhfg qual o problema com o código da disciplina? Ele não estar unique?

**Comment by Danhfg** [comment]
Sim, na reunião eu e Umberto chegamos a conclusão que é melhor colocar esse campo como unique, você discorda ?

**Comment by Confuzo** [comment]
Não, acho que é até melhor, evita que acidentalmente existam duas disciplinas com códigos iguais

**Comment by Confuzo** [comment]
@Danhfg Posso fechar essa issue?

**Comment by Confuzo** [comment]
@Danhfg corrigi já
