### ISSUE TITLE
Endpoint GET tutorias/ não mostra as tutorias desativadas

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#50]
A documentação não é clara se eu removo ou desativo. Em teste, depois de tentar desativar a tutoria 3 pelo endpoint `https://epet.imd.ufrn.br:8443/api/tutoria-remove/3` a tutoria foi apagada apesar de que na documentação fala que é desativada.

 Portanto, gostaria de saber se ocorre desativação de tutoria ou remoção. E se for remoção então por que existe o atributo `ativo`?

**Comment by Confuzo** [comment]
@Samuellucas97 ela foi desativada, o endpoint GET tutorias/ retorna apenas as ativas
