### ISSUE TITLE
criação de endpoint de meus eventos

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#51]
Criação de endpoint que permita que `usuário comum` veja todos os eventos em que ele está cadastrado

**Comment by Confuzo** [comment]
@Samuellucas97 já existe esse endpoint. 

GET /api/participantes-pessoa/{id} - Método que busca as participações em evento de uma Pessoa através do ID da PESSOA.

**Comment by Samuellucas97** [comment]
Perfeito
