### ISSUE TITLE
permitir usuário comum usar o GET /api/participantes-pessoa/{id}

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#53]
Deve-se permitir o uso do endpoint `GET /api/participantes-pessoa/{id}` para **usuário comum**.

Eu tentei usar o `idPessoa` 2 - o qual pode-se ver abaixo que existe
```
{
  "idPessoa": 2,
  "nome": "Usuario Teste",
  "cpf": "56172279475",
  "tipo_usuario": {
    "idTipo_usuario": 3,
    "nome": "comum"
  },
  "usuario": {
    "idUsuario": 13,
    "email": "comum@gmail.com"
  }
}
```
Porém recebi como resposta

```
{
  "timestamp": "2020-05-18T04:55:07.286+0000",
  "status": 403,
  "error": "Forbidden",
  "message": "Forbidden",
  "path": "/api/participantes-pessoa/2"
}
```

**Comment by Danhfg** [comment]
Tive analisando e percebi que tanto em participantes, quanto em organizadores, um usuário comum deve ter autorização @Confuzo .

**Comment by Danhfg** [comment]
Para participantes salvarParticipantes é necessário uma vez que é o cadastro do usuário comum no evento, getParticipantesPessoa e  getParticipantesPorPessoa uma vez que é a forma de recuperar os eventos que o usuário comum está participando

**Comment by Danhfg** [comment]
Já para Organizadores creio que apenas salvarOrganizadores e removerOrganizadores() não possam ter permissão para o usuário comum, uma vez que ele pode ser um organizador dos eventos.

**Comment by Danhfg** [comment]
Concorda com os pontos apontados @Confuzo ?

**Comment by Confuzo** [comment]
@Danhfg sim concordo!
