### ISSUE TITLE
O cadastro de tutoria ministrada está como GET e deve ser POST

### ISSUE THREAD

**Issue by Danhfg** [PETCC-UFRN/ePET#61]
O correto deveria ser Post @Confuzo 
https://github.com/PETCC-UFRN/ePET/blob/af0490c57fb9eac46963acedc39189da65e30551/src/main/java/br/ufrn/ePET/controller/Tutoria_MinistradaController.java#L112

**Comment by Confuzo** [comment]
@Danhfg Não é bug, fiz assim para que não fosse possível passar um payload ao sistema
