### ISSUE TITLE
Dúvida na pesquisa de disciplinas em tutoria

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#62]
Eu usei o endpoint `GET /api/pesquisar-disciplina-tutoria/{search}`  como usuário comum ele me retornou tutorias inativas. 
```
0: { 
idTutoria: 7
petiano: {...},
disciplina: {...}
ativo: true
},
1: {
idTutoria: 10
petiano: {...}
disciplina: {...}
ativo: false
},
2: {idTutoria: 11
petiano: {…}
disciplina: {...}
ativo: false
}
```
Eu pesquisei a disciplina chamada `terceiro`. Portanto, está correto isso ou deveria retornar apenas as tutorias ativas? Por outro lado, se isso for correto, gostaria de ter um endpoint para fazer essa pesquisa como usuário

**Comment by Danhfg** [comment]
Corrigi em #63
