### ISSUE TITLE
Problema de conexao com o banco de dados

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#72]
Ao tentar me conectar com o login `teste@gmail.com` e senha `tutor_teste852` e recebi esse erro

{
  "timestamp": "2020-05-27T13:22:58.226+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection",
  "path": "/api/sign-in/"
}

**Comment by Danhfg** [comment]
Isso pode ter ocorrido pelo problema que estava acontecendo no servidor ?
