### ISSUE TITLE
Erro a buscar em petianos-pessoa

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#75]
Eu era o usuário `teste_petiano@gmail.com` e requisitei `https://epet.imd.ufrn.br:8443/api/petianos-pessoa/6`.

```
{
"status":500,
"error":"Internal Server Error",
"message":"query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3","path":"/api/petianos-pessoa/6"
}
```

**Comment by Danhfg** [comment]
Isso ocorreu pois sem querer cadastrei 3 petianos para o usuário teste_petiano, se puder apagar no banco @Confuzo resolveria, os ids petianos são: 20 e 21.

**Comment by Confuzo** [comment]
Resolvido
