### ISSUE TITLE
Problema na rota de validacao de certificado 

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#82]
Ao tentar usar a rota `GET /api/certificado/validar/{hash}` eu recebi 

```
{
  "status": 403,
  "error": "Forbidden",
  "message": "Access Denied",
  "path": "/api/certificado/validar/mnm"
}
```
Acredito que o correto é que ele esteje liberada para todo mundo.

**Comment by Danhfg** [comment]
O certificado foi gerado previamente ?

**Comment by Danhfg** [comment]
Está com um comportamento muito estranho, uma vez que, testando na minha máquina local, é como se a requisição nem chegasse e já retorna isso
