### ISSUE TITLE
Erro na edicao de evento

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#91]
Quando eu (`teste@gmail.com` / tutor) tentei editar o evento de  `idEvento = 7` recebi essa mensagem de erro:

```
{
"status":500,"error":"Internal Server Error",
"message":"Essa pessoa já está organizando o evento!",
"path":"/api/eventos-cadastrar"
}
```

**Comment by Danhfg** [comment]
Eu tinha esquecido que a rota de cadastro é a mesma de edição, dai ele tenta cadastrar novamente o usuário como organizador, irei concertar.

**Comment by Danhfg** [comment]
- [ ]
