### ISSUE TITLE
usuario comum organizador nao tem permissao de ver pessoas

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET#93]
Para que um usuário comum (organizador de um evento) possa adicionar participantes ao evento. Ele precisa ter acesso aos endpoints  `get participantes-evento/{id_evento}` e `get pessoas`. Atualmente a mensagem é acesso negado
```
{
"status":403,
"error":"Forbidden",
"message":"Forbidden",
"path":"/api/pessoas"
}
```
e 
```
{
"status":403,
"error":"Forbidden",
"message":"Forbidden",
"path":"/api/participantes-evento/7"
}
```

Eu usei o usuário `comum@gmail.com`

**Comment by Danhfg** [comment]
O git pessoas é para adicionar um organizador/participante ? Eu creio que seja melhor que um usuário comum não tenha essas permissões, apenas a de edição do evento, o que você acha ?
